### ISSUE TITLE
Update the HMDB test for outdated identifiers

### ISSUE THREAD

**Issue by egonw** [wikipathways/WikiPathwaysCurator#1]
Which currently fails because of the new HMDB identifier scheme.

See https://github.com/BiGCAT-UM/WikiPathwaysCurator/commit/249e873f24cf82164c594136c9d818bfd5333926

**Comment by DeniseSl22** [comment]
I looked at your [example for secondary ChEBI test](https://github.com/BiGCAT-UM/WikiPathwaysCurator/commit/3c66dd018d27d6dc5cc666d6c9b067345e0647a5) for Jenkins, created it for HMDB now [file](https://github.com/egonw/denise/blob/master/HMDBSecMetabolites.java). 

I also filed an issue in the bridgedb/create-bridgedb-metabolites repository; so I will close that issue (#8).

I have 2 questions remaining:
1. What does line 68 do (and how should I adapt it for HMDB?)
2.Would you like this as a commit, or could we insert it in Jenkins together @egonw (I would like to see how to do this properly)?

**Comment by DeniseSl22** [comment]
Previous info from issue in wrong repository:

In order to remove the secondary IDs from HMDB, I wrote a [script](https://github.com/egonw/denise/blob/master/deprecatedHMDBsPythonscript.py) in Python to obtain the secondary IDs from the XML file. [The output (CSV)](https://github.com/egonw/denise/blob/master/HMDBDataSecondaryAll_Final.txt) with in the first column Secondary ID and in the second column Primary ID, can now be run with a similar Jenkins test as the one for ChEBI.

The CSV should be updated with new HMDB updates (latest on was run on the end of march release of 2018).
