### ISSUE TITLE
GPML DataNodes without a "Type"

### ISSUE THREAD

**Issue by marvinm2** [wikipathways/WikiPathwaysCurator#11]
Encountered this when converting GPML to SVG. The parsing lead to KeyErrors for DataNodes without a "Type". Is it allowed to have DataNodes without a 'Type'? 
[gpmlwitherrors.txt](https://github.com/BiGCAT-UM/WikiPathwaysCurator/files/4560924/gpmlwitherrors.txt)

**Comment by egonw** [comment]
The matching query:

```sparql
SELECT ?node WHERE {
  ?node a gpml:DataNode ;
        gpml:type "Unknown"^^xsd:string .
}
```

**Comment by marvinm2** [comment]
No, they are not defined as "Unknown". They are not existing. There is no gpml:type for this particular list of nodes I talk about

**Comment by egonw** [comment]
Then there must be more than one type of problem :(

**Comment by marvinm2** [comment]
Indeed, these 'unknown' datanodes are a separate thing than the problem I describe. I am talking about the GPML files in which there are datanodes without a type (so also not an 'unknown')

**Comment by mkutmon** [comment]
@marvinm2 I found the problem. data nodes with type "Unknown" are saved in GPML without a type. So if there is no type, the type is by default unknown. 
This also defined in the XSD Schema:
<xsd:attribute name="Type" type="xsd:string" default="Unknown">

That means that this needs to be fixed in the converter and it's not a curators error.

**Comment by egonw** [comment]
Confirmed. The GPMLRDF generator always has a `gpml:type` predicate, which explains why I only had a test for `Unknown`.
